project_id = "nwohehoountzfudzygqg"

[functions.ai-chat]
verify_jwt = false

[functions.standardize-roles]
verify_jwt = false

[functions.ai-job-description-generator]
verify_jwt = false

[functions.ai-skills-assessment]
verify_jwt = false

[functions.employee-mobility-planning]
verify_jwt = false

[functions.development-pathways]
verify_jwt = false

[functions.dynamic-role-upload]
verify_jwt = false

[functions.flexible-role-upload]
verify_jwt = false

[functions.employee-upload-ai]
verify_jwt = false

[functions.employee-upload-progress]
verify_jwt = false

[functions.ai-skills-assessment-bulk]
verify_jwt = false

[functions.ai-skills-assessment-progress]
verify_jwt = false

[functions.employee-mobility-planning-bulk]
verify_jwt = false

[functions.employee-mobility-planning-progress]
verify_jwt = false

[functions.development-pathways-bulk]
verify_jwt = false

[functions.development-pathways-progress]
verify_jwt = false